// <auto-generated />
namespace Videly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpropertiestomovieclasscreategenretableandlinkthem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpropertiestomovieclasscreategenretableandlinkthem));
        
        string IMigrationMetadata.Id
        {
            get { return "201608251913116_add properties to movie class, create genre table, and link them"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
